version: 0.2

phases:
  install:
    commands:
      #- Get-ChildItem -Path c:\Users
      #- echo f | xcopy /f /y .\settings.xml c:\.m2\settings.xml
      - get-childitem -path env:* | sort-object name
      - get-childitem -path $env:CODEBUILD_SRC_DIR/.m2/* -Depth 1 -ErrorAction SilentlyContinue
      - New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.m2
      #- aws s3 cp s3://invoice-releases/settings.xml $env:USERPROFILE/.m2/settings.xml
      #- aws s3 cp s3://invoice-releases/settings-security.xml $env:USERPROFILE/.m2/settings-security.xml
      #- get-childitem -path $env:USERPROFILE/.m2 -Depth 1 -ErrorAction SilentlyContinue
  pre_build:
    commands:
    #- New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.m2
    #- get-childitem -path $env:USERPROFILE/.m2
    #- get-childitem -path $env:CODEBUILD_SRC_DIR/.m2
    #- Copy-Item $env:CODEBUILD_SRC_DIR\.m2\* -Destination $env:USERPROFILE\.m2 -Recurse
    #- get-childitem -path $env:USERPROFILE/.m2
  build:
    commands:
      #- mvn install -Dtest="*,!receiptsapi.util.image.ReceiptScannerTest"
      - cd 0.9.4
      - mvn install
  post_build:
    commands:
      - get-childitem -path $env:USERPROFILE/.m2 -Depth 1 -ErrorAction SilentlyContinue
      - get-childitem -path $env:CODEBUILD_SRC_DIR/.m2 -Depth 1 -ErrorAction SilentlyContinue
      #- aws s3 cp $env:CODEBUILD_SRC_DIR/0.9.4/target/CentsoftInvoice-2.0.war s3://invoice-releases/latest/CentsoftInvoice-2.0.war

cache:
  paths:
    - ./.m2/**/*
artifacts:
  base-directory: 0.9.4/target
  files:
    - '*'
  name: release_$([uri]::EscapeUriString("#"))$([int][double]::Parse((Get-Date -UFormat %s)))_$(Get-Date -f "yyyy-MM-dd_HH.mm.ss")
